version: '3'
services:
  web:
    build: .
    ports:
      - "5001:80/tcp"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: "postgres:14-alpine"
    expose:
      - "5432/tcp"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_PASSWORD: stskpgsqlpasswd
