version: '2.1'
services:
  web:
    build:
      context: ./
      dockerfile: stockstack.Dockerfile
    ports:
      - "5080:5080/tcp"
      - "5443:5443/tcp"
    volumes:
      - .:/app
      - ./config:/app/config:Z
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "postgres:14-alpine"
    ports:
      - "5432:5432/tcp"
    expose:
      - "5432/tcp"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data:Z
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U stockstack" ]
      interval: 5s
      timeout: 5s
      retries: 20
    environment:
      POSTGRES_USER: stockstack
      POSTGRES_PASSWORD: stockstack
      POSTGRES_DB: stockstack

  wallet:
    build:
      context: ./
      dockerfile: jwallet.Dockerfile
